services:

    ea3cv-4:
        container_name: ea3cv-4
        restart: unless-stopped
        image: dxspider:v157r633-test
        ports:
            - "7304:7300"
            - "7304:7301"
            - "7304:7302"
        volumes:
            # Binds para persistencia de datos del Nodo 4  
            - "/root/volumenes/dxspider/nodo-4/msg:/spider/msg"
            - "/root/volumenes/dxspider/nodo-4/local_data:/spider/local_data"
            - "/root/volumenes/dxspider/nodo-4/local_cmd:/spider/local_cmd"
            - "/root/volumenes/dxspider/nodo-4/connect:/spider/connect"
            - "/root/volumenes/dxspider/nodo-4/scripts:/spider/scripts"
            - "/root/volumenes/dxspider/nodo-4/local:/spider/local"
            - "/root/volumenes/dxspider/common/contrib:/spider/contrib"
            # Binds para persistencia de datos comunes a todos los Nodos
            - "/root/volumenes/dxspider/common/filter:/spider/filter"
            # Binds para inyectar configuraciones comunes a todos los nodos
            #- "${PWD}/dxspider-nodos/common/filter/spots/in_node_default.pl:/spider/filter/spots/in_node_default.pl"
            #- "${PWD}/dxspider-nodos/common/filter/spots/node_default.pl:/spider/filter/spots/node_default.pl"

networks:
  dxspider_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.60.0.0/24
