#!/usr/bin/perl

#
# Makes the Statistics of the Spots by User and day
# Put in sysop user's crontab
# Usage: ./make_stat_call_spots <NODE>
#
# Created by EA3CV
#
# 20201126 v0.4
#

use 5.10.1;
use strict;
use Time::Piece;
use Time::Seconds;
use Data::Dumper;

my $server = $ARGV[0];

#my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time - 60 * 60 * 24);
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);

$year += 1900;
$mon++;

my $y = $year;
my $d = sprintf("%03s", $yday);

my $time = Time::Piece->new;
$time  = $time - ONE_DAY;
my $fecha = $time->ymd("");

my $log_dat = "/spider/local_data/spots/$y/$d.dat";

my $sum = 0;
my @array;
open(my $data, '<', $log_dat) or die "No puedo abrir el fichero '$log_dat' $!\n";

while (my $line = <$data>) {
   chomp $line;

   my @fields = split "\\^" , $line;
   if ($fields[7] eq $server){
       push @array, $fields[4]
   }
}
#say @array;

# Contamos los spots por call

my $count;
my %count;
my $total = 0;

foreach my $call (@array) {
   $count{$call}++;
   $total++;
    }

open(LOG,">/spider/local_data/spots/stat_call_spots_$fecha.txt");

say LOG " ";
say LOG "   Spots generated by user in the day: $fecha ";
say LOG " ";
say LOG "   Call       Spots";
say LOG "   ---------  -----";

foreach my $call (sort keys %count) {
   say LOG sprintf("   %-10s  %3s", $call, $count{$call});
}

say LOG " ";
say LOG "   Total:       $total";
say LOG " ";

close LOG;

