
name: CI Servicios OVH

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  copy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Ficheros Nodo 2
        run: cp -r dxspider-nodos/nodo-2 /root/volumenes/dxspider
    
      - name: Ficheros Nodo 3
        run: cp -r dxspider-nodos/nodo-3 /root/volumenes/dxspider

      - name: Ficheros Nodo 7
        run: cp -r dxspider-nodos/nodo-7 /root/volumenes/dxspider

      - name: Ficheros Nodo 8
        run: cp -r dxspider-nodos/nodo-8 /root/volumenes/dxspider

      - name: Ficheros Nodo 9
        run: cp -r dxspider-nodos/nodo-9 /root/volumenes/dxspider

      - name: Ficheros Common Contrib
        run: cp -r dxspider-nodos/common /root/volumenes/dxspider

      - name: Ficheros DXSpider-Watch
        run: cp -r dxspider-watch /root
      
      - name: Hacer ejecutable el Script
        run: chmod +x /root/dxspider-watch/dt.sh

      - name: Hacer ejecutable los entrypoint
        run: chmod +x /root/dxspider-watch/mojo/entrypoint.sh

      - name: Hacer ejecutable los entrypoint
        run: chmod +x /root/dxspider-watch/on-demand/entrypoint.sh

  #build:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Deploy de contenedores DXSpider
        run: sudo docker-compose up -d
        
