name: CI/CD DXSpider

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  copy-files:
    runs-on: [self-hosted, repo-vps-ovh-test]

    steps:
      - uses: actions/checkout@v4

      - name: Sincronizar Nodo 4 al volumen
        run: |
          set -euo pipefail
          src="$GITHUB_WORKSPACE/dxspider/nodo-4"
          dest="/root/volumenes/dxspider/nodo-4"
          install -d -m 755 "$dest"
          rsync -a --delete "$src"/ "$dest"/

  deploy:
    runs-on: [self-hosted, repo-vps-ovh-test]
    needs: copy-files
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Quita este paso si no usas GHCR/registro privado
      - name: (Opcional) Login GHCR
        if: env.GHCR_PAT != ''
        run: echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}

      - name: Levantar contenedores
        timeout-minutes: 10
        run: |
          set -euo pipefail
          if docker compose version >/dev/null 2>&1; then
            docker compose pull || true
            docker compose up -d
            docker compose ps -a
          else
            docker-compose pull || true
            docker-compose up -d
            docker-compose ps -a
          fi
