
name: CI Servicios OVH

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    #env:
      #SAMBA: ${{ secrets.SAMBAPASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: sudo docker-compose up -d
        
