
name: CI Servicios OVH

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  copy:
    runs-on: self-hosted
    steps:
      - name: Ficheros Nodo 3
        run: cp -r dxspider-nodos/nodo-3 /root/volumenes/dxspider

      - name: Ficheros Nodo 7
        run: cp -r dxspider-nodos/nodo-7 /root/volumenes/dxspider
      
      - name: Ficheros DXSpider-Watch
        run: cp -r dxspider-watch /root
      
      - name: Hacer ejecutable
        run: chmod +x /root/dxspider-watch/dt.sh

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: sudo docker-compose up -d
        
