name: CI/CD de los contenedores DXSpider

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  copy-files:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Ficheros Nodo 4
        run: cp -r nodo-4 /root/volumenes/dxspider

  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Deploy de contenedores DXSpider ITU
        run: docker compose up -d
